version: '3.8'

services:
  postgres-keycloak:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_LOG_LEVEL: DEBUG
      KC_LOG_CONSOLE_COLOR: true
      KC_LOG_CONSOLE_OUTPUT: default
    volumes:
      - ./realms/smart-hcs.json:/opt/keycloak/data/import/smart-hcs.json:ro
    ports:
      - 9080:8080
    depends_on:
      - postgres-keycloak
    restart: unless-stopped

volumes:
  postgres_data:
